### ISSUE TITLE
We have to change language two times to actually change language

### ISSUE THREAD

**Issue by Camroku** [ardatdev/artadosearch-source#2]
When a language is selected, and we want to use another language, we have to change language two times.
For example:

![1](https://user-images.githubusercontent.com/79412062/132951180-8269f929-5802-4d43-84e2-993bb9a4b56b.png)
English is selected.

![2](https://user-images.githubusercontent.com/79412062/132951182-9b1f3f0d-d53f-424f-9e3d-a0df04082514.png)
I click Turkish from the selectbox, but it just deletes the cookie and the UI is still English.

![3](https://user-images.githubusercontent.com/79412062/132951184-74c10b4c-5dbe-4e4b-90ea-695085fc9446.png)
I click Turkish again, and it finally switches to Turkish.

**Comment by ardatdev** [comment]
I fixed the issue. I will share the source code soon.

**Comment by ardatdev** [comment]
I fixed the issue. I will share the source code soon.
